# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_users_quotecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='quotecount',
            new_name='count',
        ),
    ]
