# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last',
            new_name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
