# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_quotes_quotesofusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='quotecount',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
