# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170502_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='count',
        ),
    ]
