# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_remove_users_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='count',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
