# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripsofusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='trips',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid_trip', to='first_app.Users'),
        ),
        migrations.AddField(
            model_name='tripsofusers',
            name='tripid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripkey', to='first_app.Trips'),
        ),
        migrations.AddField(
            model_name='tripsofusers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlink', to='first_app.Users'),
        ),
    ]
